### PR TITLE
Incorporating review comments

### PR DESCRIPTION
**Pull request by preetkaran20**
Signed-off-by: Karan Preet Singh Sasan <preetkaran20@gmail.com>

### CODE REVIEW

**Comment by preetkaran20** [comment]
Hi @thc202

Incorporated the review comments, please have a look.

thanks,
Karan

**Comment by thc202** [comment]
Looks good to me.

**Comment by preetkaran20** [comment]
> Are you going to release a new version or should we go ahead with the add-on already released?

I am thinking of updating the binary in the same release version.

**Comment by thc202** [comment]
OK, let us know when that's done.

**Comment by preetkaran20** [comment]
> OK, let us know when that's done.

I have done it.

**Pull request merged**
